AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Fragmento de plantilla para documentar la creación 
  del Cluster Elástico de Amazon DocumentDB.

# ==================================================================
# Parámetros (Inputs)
# ==================================================================
Parameters:
  VpcId:
    Type: String
    Description: "El ID de la VPC donde reside el cluster."
    Default: "vpc-0d8e000397287b2e9"
  PrivateSubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: "Una subred privada donde vive el cluster."
  PrivateSubnetB:
    Type: AWS::EC2::Subnet::Id
    Description: "Una segunda subred privada en otra AZ."
  LambdaSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "El ID del Grupo de Seguridad de la Lambda."

# ==================================================================
# Recursos (Lo que se crea)
# ==================================================================
Resources:

  # -----------------------------------------------------------------
  # 1. Grupo de Seguridad para DocumentDB
  # Define quién puede conectarse al cluster (solo la Lambda).
  # -----------------------------------------------------------------
  DocDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Grupo de seguridad para DocumentDB (permite entrada desde la Lambda)"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # Regla de Entrada: Permite conexiones en el puerto 27017 SÓLO desde la Lambda.
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          SourceSecurityGroupId: !Ref LambdaSecurityGroupId
      Tags:
        - Key: Name
          Value: 	puj_documentdb_sg

  # -----------------------------------------------------------------
  # 2. El Cluster Elástico de DocumentDB
  # Esta es la definición de la base de datos que creaste.
  # -----------------------------------------------------------------
  TransmilenioDBCluster:
    Type: AWS::DocDB::Cluster
    Properties:
      ClusterName: "puj-documentdb-cluster" #
      AdminUserName: "pujadmin" 
      AdminUserPassword: "Postgrado147"
      AuthType: "Password"
      BackupRetentionPeriod: 7
      DbInstanceCount: 1 # (Número de instancias por shard)
      DbInstanceCapacity: 2 # (Capacidad vCPU por instancia)
      ShardCount: 2 # (Número de shards)
      DbSubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      PreferredBackupWindow: "02:00-03:00"
      PreferredMaintenanceWindow: "sun:03:00-sun:04:00"
      VpcSecurityGroupIds:
        - !Ref DocDBSecurityGroup # Usa el Grupo de Seguridad creado arriba

# ==================================================================
# Salidas (Outputs)
# ==================================================================
Outputs:
  DocumentDBEndpoint:
    Description: "Endpoint del cluster de DocumentDB"
    Value: !GetAtt TransmilenioDBCluster.Endpoint
  DocumentDBPort:
    Description: "Puerto del cluster de DocumentDB"
    Value: !GetAtt TransmilenioDBCluster.Port