AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Proyecto Transmilenio: Lambda para procesar coordenadas de buses
  y almacenarlas en Amazon DocumentDB.

Parameters:
  LambdaRole:
    Type: String
    Description: "El ARN del rol IAM que la función Lambda usará."
  DocDBSecretArn:
    Type: String
    Description: "El ARN del secreto en AWS Secrets Manager que contiene el user/pass de DocumentDB."
  VpcId:
    Type: String
    Description: "El ID de la VPC donde están DocumentDB y la Lambda."
  PrivateSubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: "Una subred privada donde correrá la Lambda."
  LambdaSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "El Grupo de Seguridad para la Lambda. Este grupo debe tener permiso de salida (outbound) a DocDB en el puerto 27017."

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256

Resources:
  # -----------------------------------------------------------------
  # 1. Capa (Layers)
  # -----------------------------------------------------------------
  PymongoLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pymongo-layer
      Description: "Capa de dependencias con la librería pymongo"
      ContentUri: layers/pymongo-layer/
      CompatibleRuntimes:
        - python3.10
      BuildMethod: python3.10 # SAM usará pip para instalar lo que esté en requirements.txt
  # -----------------------------------------------
  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: request-layer
      Description: "Capa de dependencias con la librería requests"
      ContentUri: layers/request-layer/
      CompatibleRuntimes:
        - python3.10
      BuildMethod: python3.10 # SAM usará pip para instalar lo que esté en requirements.txt

  # -----------------------------------------------------------------
  # 2. Lambda Function puj-simulador-transmilenio
  # -----------------------------------------------------------------
  BusLocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: puj-lambda-api
      Runtime: python3.10
      CodeUri: src/lambda_functions/bus_location_processor/
      Handler: app.lambda_handler # (El archivo se llama app.py y la función lambda_handler)
      Role: !Ref LambdaRole
      Timeout: 20
      MemorySize: 256
      Layers:
        - !Ref PymongoLayer # Adjunta la capa de pymongo
      Environment:
        Variables:
          REGION_NAME: !Ref RegionName
          CA_CERT_PATH: /opt/python/global-bundle.pem
    
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetA

  # -----------------------------------------------------------------
  # 2. Lambda Function puj-getpositions
  # -----------------------------------------------------------------
  BusLocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: puj-lambda-getpositions
      Runtime: python3.10
      CodeUri: src/lambda_functions/get-positions/
      Handler: app.lambda_handler # (El archivo se llama app.py y la función lambda_handler)
      Role: !Ref LambdaRole
      Timeout: 20
      MemorySize: 256
      Layers:
        - !Ref PymongoLayer # Adjunta la capa de pymongo
      Environment:
        Variables:
          REGION_NAME: !Ref RegionName
          CA_CERT_PATH: /opt/python/global-bundle.pem
    
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetA
        
  # -----------------------------------------------------------------
  # 3. Lambda Function puj-lambda-api
  # -----------------------------------------------------------------
  PujSimulatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: puj-simulador-transmilenio
      Runtime: python3.10
      CodeUri: src/lambda_functions/simulador/
      Handler: app.lambda_handler # (El archivo se llama app.py y la función lambda_handler)
      Role: !Ref LambdaRole
      Timeout: 20
      MemorySize: 256
      Layers:
        - !Ref RequestsLayer # Adjunta la capa de pymongo
      Environment:
        Variables:
          API_URL: !Ref ApiGatewayURL
          API_KEY: !Ref ApiKey
          BUS_ID: BUS_101
    
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetA
   
Outputs:
  BusLocationFunctionName:
    Description: "Nombre de la función Lambda"
    Value: !Ref BusLocationFunction
  LambdaSimulatorArn:
    Description: ARN de la Lambda del Simulador
    Value: !GetAtt PujSimulatorLambda.Arn
  BusLocationFunctionArn:
    Description: "ARN de la función Lambda"
    Value: !GetAtt BusLocationFunction.Arn